### ISSUE TITLE
Question about input matrix

### ISSUE THREAD

**Issue by chowdharyk** [kundajelab/ChromDragoNN#4]
Hi, if I want to train a model to predict binary accessibility in my own cell types of interest, can you provide some guidance for how to preprocess my data? Where do I input the binary matrix of accessibility in each cell type + bed file of peaks into your preprocess pipeline to generate the .joblib files needed to input into the model? 

Thanks for your help!

**Comment by suragnair** [comment]
Hi, I apologize for not making the code very easy to use. Would it be possible for you to prepare your data in the following format, sorted as usual with `bedtools sort`. 

```
CHR    START  END    INDEX  task1  task2  ...  taskM
chr1   50     1050   1      0      0           0
chr1   1000   2000   1      1      0           1
chr2   100    1100   1      1      0           1
 ```

If so, I'll write up a script that takes this matrix, a reference fasta and converts it to the file format used by data loader.

**Comment by chowdharyk** [comment]
Sure, that should be easy for me to do with my data. That would be amazing -- thanks so much for your help with this!

**Comment by suragnair** [comment]
Awesome! Just modified the format a bit and removed the INDEX column.

**Comment by suragnair** [comment]
I have added a few scripts to the `preprocess` directory and accompanying instructions in the README. I have briefly tested the scripts but there is a slight chance things may break. Please run the scripts and let me know if things go smoothly. Thanks!

**Comment by chowdharyk** [comment]
Thanks so much -- really appreciate the help! I will try running them and let you know

**Comment by suragnair** [comment]
Did it work?

**Comment by chowdharyk** [comment]
Sorry for the late reply -- yes, it worked perfectly! Thanks again for your help with this!
