### ISSUE TITLE
color2ctype is missing from tSNE notebook

### ISSUE THREAD

**Issue by omarnmohd** [kundajelab/ChromDragoNN#5]
Hello I was wondering if you can make the color2ctype labels available for the tSNE notebook plots?

thank you,

Omar

**Comment by suragnair** [comment]
Hi, it’s available in the supplementary material. In particular there is a TSV with what you need. Let me know if you have any difficulties. 

https://academic.oup.com/bioinformatics/article/35/14/i108/5529138#supplementary-data

**Comment by suragnair** [comment]
Sorry just realized what you meant. Can you try this code?

```
colors = [rna['metadata']['color'][int(k.split('_')[1])] for k in d]
ctypes = [rna['metadata']['cell_type'][int(k.split('_')[1])] for k in d]

color2ctype = {}
for cl,ct in zip(colors,ctypes):
    if cl not in color2ctype:
        color2ctype[cl] = ct
    else:
        if ct not in color2ctype[cl]:
            color2ctype[cl] += '/' + ct
```

**Comment by omarnmohd** [comment]
Thank you so much !

**Comment by suragnair** [comment]
Did it work?

**Comment by omarnmohd** [comment]
I think there should be a line before this linking   "rna" to the data "Nair.374.sup.4.tsv"


I solved this issue by just hard coding the options, although I would be glad to test out this code to add to the notebook for future reference.

my hardcode is this btw:

`def convOM2c(c):
    switcher = {
        0: '#27AE60',
        1: '#377031',
        2: '#4178AE',
        3: '#4EBEA4',
        4: '#55A354',
        5: '#60B0C8',
        6: '#678C69',
        7: '#83601C',
        8: '#8E7CC3',
        9: '#909497',
        10: '#924965',
        11: '#AF5B39',
        12: '#B65C73',
        13: '#C2655D',
        14: '#C4AFB8',
        15: '#C58DAA',
        16: '#C5912B',
        17: '#D49B2D',
        18: '#D54444',
        19: '#F1C232',
        20: '#FF7850',
        21: '#FF8B48',
        22: '#FF9D0C'
    }
    return switcher.get(c, "Invalid Color")


def convOM2cell(c):
    switcher = {
        0: 'Lymphoblastoid',
        1: 'Leukemia/Lymphoma',
        2: 'Chorion/Ectoderm/ES-derived/Mesoderm',
        3: 'Spleen/Thymus',
        4: 'T-cell',
        5: 'Lung',
        6: 'B-cell',
        7: 'Brain/Eye/Neuron/Neurosphere/Spinal cord',
        8: 'Adrenal/Follicular/Islet/Stem/Thyroid',
        9: 'Melanocyte/Melanoma/Nevus',
        10: 'ESC',
        11: 'Adipocyte/MSC/Preadipocyte',
        12: 'Chondrocyte/Fibroblast/Stromal',
        13: 'Aorta/Atrium/Heart/Muscle/Satellite/Skeletal/Smooth/Tongue/Ventricle',
        14: 'Amnion/Placenta/Umbilical cord/Uterus',
        15: 'Colon/Esophagus/Liver/Small Intestine/Stomach',
        16: 'Astrocyte',
        17: 'Neuroblastoma',
        18: 'Endothelial',
        19: 'Bladder/Kidney',
        20: 'Adenocarcinoma',
        21: 'Carcinoma',
        22: 'Epithelial/Keratinocyte/Skin'
    }
    return switcher.get(c, "Invalid Label")


plt.rcParams["axes.titlesize"] = 40
plt.rc('font', family='serif')

plt.subplots(1,2, figsize=(40,15))
plt.subplot(1,2,1)
plt.scatter(rna_reduced[:,0], rna_reduced[:,1], c=rna['metadata']['color'],  s=100)
frame = plt.gca()
frame.get_xaxis().set_visible(False)
frame.get_yaxis().set_visible(False)
plt.title('RNA-seq', y=1.03)

plt.subplot(1,2,2)
plt.scatter(preds_accs_reduced[:,0], preds_accs_reduced[:,1], c=rna['metadata']['color'],  s=100)
frame = plt.gca()
frame.get_xaxis().set_visible(False)
frame.get_yaxis().set_visible(False)
plt.title('Predicted Accessibility', y=1.03)


for cl in range(23):
    plt.bar(0, 0, color=convOM2c(cl), label=convOM2cell(cl), linewidth=0)
    

plt.legend(loc='upper center', bbox_to_anchor=(-0.1, 1.5), fontsize=25, ncol=3)   



plt.savefig('tsne.pdf', bbox_inches='tight')
`

**Comment by suragnair** [comment]
You shouldn't need the supplementary TSV as it is contained within the `rna` variable in the notebook (which loads from the joblib object).

**Comment by omarnmohd** [comment]
ok I will uncomment the code where rna is defiend and run the snippet.

**Comment by omarnmohd** [comment]
I get an error stating that 

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-13-e3472934051a> in <module>
      3 rna = rna_quant_data_impute
      4 
----> 5 colors = [rna['metadata']['color'][int(k.split('_')[1])] for k in d]
      6 ctypes = [rna['metadata']['cell_type'][int(k.split('_')[1])] for k in d]
      7 

NameError: name 'd' is not defined
```

**Comment by suragnair** [comment]
```color2ctype = {}
for cl,ct in zip(rna['metadata']['color'], rna['metadata']['cell_type']):
    if cl not in color2ctype:
        color2ctype[cl] = ct
    else:
        if ct not in color2ctype[cl]:
            color2ctype[cl] += '/' + ct
```

**Comment by omarnmohd** [comment]
yes the new script works now. thank you!
