### ISSUE TITLE
GRCh38 model

### ISSUE THREAD

**Issue by gianfilippo** [kundajelab/ChromDragoNN#9]
Hi,

do you have a pretrained model based on GRCh38 ?

Thanks
Gianfilippo

**Comment by suragnair** [comment]
Unfortunately not

**Comment by gianfilippo** [comment]
thanks
Gianfilippo

**Comment by akundaje** [comment]
Note that you can use the model on any genome version since it only needs a
sequence and regulator expression input. The sequence can be from any human
genome version

**Comment by gianfilippo** [comment]
Hi,

yes, I understand I can train the model on GRCh38 based data.
I was hoping you already had a GRCh38 trained model I could use for
prediction.

Perhaps, if the gene definition for the predictors you use in your model is
the same,, I could use the expression levels I have as input and get hg19
based DHS levels from the available model, then, convert the results to
GRCh38?

I may have already asked this, but how do you handle batch effects ?

Thanks
Gianfilippo

**Comment by akundaje** [comment]
My point is training on GRCh38 or GrCh37 doesn't matter. A trained model
can be used for prediction on any sequence (from any human genome version
or synthetic sequences) and cell type with available expression data. So if
you want to make predictions you can use the trained model as is.

We don't handle batch effects or data quality differences in this version.
For now, it would be to be taken care of in the data preprocessing.

We will be explicitly modeling these effects in the next iterations of this
work.

Anshul
